apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "oxalis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.portextraArgs.protocol }}
      name: {{ .Values.service.portextraArgs.name }}
  selector:
    {{- include "oxalis.selectorLabels" . | nindent 4 }}
