# Default values for oxalis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: infotechops/oxalis
  # repository: norstella/oxalis
  pullPolicy: Always
  tag: latest
  
nameOverride: oxalis
fullnameOverride: oxalis

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}


podAnnotations:
  app: oxalis

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  portextraArgs:
    name: http
    protocol: TCP

nginx-ingress:
  enabled: true
  controller:
    name: controller
    image:
      registry: registry.k8s.io
      image: ingress-nginx/controller
      tag: "v1.8.2"
      pullPolicy: IfNotPresent
    containerName: controller  
    containerPort:
      http: 80
      https: 443
    # config: 
    #   data:
    #     ssl-passthrough=true  
    dnsPolicy: ClusterFirst
    ingressClassResource:
      enabled: true
      controllerValue: "k8s.io/ingress-nginx"
    ingressClass: nginx  
    kind: Deployment
    updateStrategy: 
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
    replicaCount: 1  
    minAvailable: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi     
      limits:
        cpu: 1
        memory: 500Mi  


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

livenessProbe:
  httpGet:
    path: /
  initialDelaySeconds: 21  
readinessProbe:
  httpGet:
    path: / 
  initialDelaySeconds: 21  

nodeSelector: 
  kubernetes.io/hostname: docker-desktop

tolerations: []

affinity: 
  podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: oxalis
              app.kubernetes.io/name: oxalis
          namespaces:
          - default
          topologyKey: kubernetes.io/hostname
        weight: 1